# Generated by Django 6.0.5 on 2026-06-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('preco_mensal', models.FloatField()),
                ('qualidade_video', models.CharField(max_length=30)),
                ('ativo', models.BooleanField()),
                ('quantidade_telas', models.IntegerField()),
                ('anuncio', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='streaming',
            name='categoria',
            field=models.CharField(default='Video', max_length=128),
        ),
        migrations.AddField(
            model_name='streaming',
            name='url',
            field=models.CharField(default='https://teste.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='streaming',
            name='name',
            field=models.CharField(max_length=45),
        ),
    ]
