# Generated by Django 6.0.5 on 2026-06-01 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_plano_streaming_categoria_streaming_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('data_cadastro', models.DateField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('descricao', models.CharField(max_length=255)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.plano')),
                ('streaming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.streaming')),
            ],
        ),
    ]
