# Generated by Django 6.0.5 on 2026-06-14 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_grupo_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plano',
            name='anuncio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plano',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
