# Generated by Django 6.0.5 on 2026-06-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_participante_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='senha',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participante',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
