# Generated by Django 6.0.5 on 2026-06-14 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_grupo_owner_alter_plano_anuncio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='cobranca_automatica',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='grupo',
            name='dia_vencimento',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meus_grupos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plano',
            name='anuncio',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='plano',
            name='ativo',
            field=models.BooleanField(),
        ),
        migrations.CreateModel(
            name='MembroGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_pagamento', models.BooleanField(default=False)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.grupo')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='membros',
            field=models.ManyToManyField(related_name='grupos_participo', through='dashboard.MembroGrupo', to=settings.AUTH_USER_MODEL),
        ),
    ]
