# Generated by Django 6.0.5 on 2026-06-15 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_grupo_cobranca_automatica_grupo_dia_vencimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='streaming',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.streaming'),
        ),
    ]
