# Generated by Django 6.0.5 on 2026-06-09 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_participante_senha_alter_participante_data_cadastro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participante',
            old_name='name',
            new_name='username',
        ),
    ]
