# Generated by Django 6.0.5 on 2026-06-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_merge_20260615_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='ocultar_membros',
            field=models.BooleanField(default=False),
        ),
    ]
